[package]
name = "nb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.55", features = ["derive"] }
regex = "1.12.2"
serde = "1.0.228"
serde_yaml = "0.9.34"
