[project]
name = "ez-nb"
version = "0.1.0"
description = "Notebook cli"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.2.0",
]
[project.scripts]
notebook = "notebook.py:main"
